CREATE TABLE IF NOT EXISTS credit_disputes (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  public_id CHAR(36) NOT NULL,
  user_id BIGINT UNSIGNED NULL,
  user_public_id CHAR(36) NOT NULL,
  account_data JSON NOT NULL,
  lender_name VARCHAR(255) NULL,
  account_number VARCHAR(80) NULL,
  error_type VARCHAR(255) NOT NULL,
  bureaus JSON NOT NULL,
  additional_details TEXT NULL,
  documents JSON NULL,
  status ENUM('submitted','under_review','resolved','rejected') NOT NULL DEFAULT 'submitted',
  progress_step TINYINT UNSIGNED NOT NULL DEFAULT 1,
  points_gained INT NOT NULL DEFAULT 0,
  submitted_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  resolved_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_credit_disputes_public_id (public_id),
  KEY idx_credit_disputes_user_public_id (user_public_id),
  KEY idx_credit_disputes_status (status)
);
