CREATE TABLE IF NOT EXISTS homepage_image_themes (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  image_name VARCHAR(120) NOT NULL,
  file_name TEXT NOT NULL,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_homepage_image_themes_is_active (is_active)
);
